spring:
  application:
    name: skill-tracker-authentication-jwt

  datasource:
    url: jdbc:mysql://localhost:3306/skilltracker?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: pass@word1
    jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: false
      generate-ddl: true
      show-sql: true


server:
  port: 8010


# Eureka Discovery Server Configutations
eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true