server:
  port: 8090

spring:
  application:
    name: skill-tracker-search
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: skilltracker



eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true